import { Coins, Receipt, ReceiptText, ScrollText, Table } from "lucide-react";

export const AccountsLinks = [
  { label: "Journal Entry", Icon: Coins, link: "/transaction" },
  { label: "Ledger", Icon: ScrollText, link: "/ledger" },
  { label: "Trial Balance", Icon: ReceiptText, link: "/trial-balance" },
  { label: "Financial Statement", Icon: Receipt, link: "/statement" },
];

export const InvoiceLink = [
  { label: "New Invoice", Icon: ReceiptText, link: "/invoice" },
  { label: "Invoice History", Icon: Table, link: "/invoice/history" },
];

export const AccountDrop = [
  "Cash",
  "Petty Cash",
  "Bank Account",
  "Accounts Receivable",
  "Inventory",
  "Prepaid Expenses",
  "Supplies",
  "Office Equipment",
  "Furniture and Fixtures",
  "Machinery",
  "Vehicles",
  "Land",
  "Buildings",
  "Lease Improvements",
  "Intangible Assets(e.g Patents, Trademarks)",
  "Investment",
  "Assured Income",
  "Deposits",
  "Work in Progress",
  "Raw Materials",
  "Finished Goods",
  "Construction in Progress",
  "Marketable Securities",
  "Deferred Tax Assets",

  "Account Payable",
  "Assured Liabilities",
  "Loan Payable",
  "Notes Payable",
  "Bonds Payable",
  "Deferred Revenue",
  "Unearned Payable",
  "Accrued Expenses",
  "Income Tax Payable",
  "Sales Tax Payable",
  "Interest Payable",
  "Dividends Payable",
  "Wages Payable",
  "Payroll Taxes Payable",
  "Long Term Debt",
  "Short Term Debt",
  "Customer Deposits",
  "Mortgage Payable",
  "Warranty Liabilities",
  "Lease Liabilities",
  "Deferred Tax Liabilities",
  "Common Stock",
  "Preferred Stock",
  "Retained Earnings",
  "Owner's Equity",
  "Share Capital",
  "Treasury Stock",
  "Dividends Declared",
  "Additional Paid-In Capital",
  "Other Comprehensive Income",
  "Drawings(for sole proprietorship)",
  "Partner's Capital Account(for partnership)",
  "Non-Controlling Interest(for consolidated statements)",
  "Sales Revenue",
  "Service Revenue",
  "Interest Income",
  "Dividend Income",
  "Rental Income",
  "Commission Income",
  "Consulting Income",
  "Subscription Revenue",
  "Royalty Income",
  "Gain on Sales of Asset",
  "Other Income",
  "Exchange Gain or Loss",
  "Cost of Goods Sold(COGS)",
  "Salaries and Wages",
  "Rent Expense",
  "Utility Expense",
  "Depreciation Expense",
  "Amortization Expenses",
  "Advertizing and Marketing Expense",
  "Insurance Expense",
  "Repair and Maintenance Expense",
  "Supplies Expense",
  "Travel Expense",
  "Entertainment Expense",
  "Office Supplies Expense",
  "Telephone and Internet Expense",
  "Legal and Professional Fees",
  "Interest Expense",
  "Taxes and Licenses",
  "Payroll Taxes",
  "Employee Benefits",
  "Bad Debt Expense",
  "Miscellaneous Expense",
  "Bank Fees",
  "Research and Development Expense",
  "Training and Development Expense",
  "Transportation Expense",
  "Vehicle Expense",
];
